### ISSUE TITLE
Claytech Crash, not loading[BUG]

### ISSUE THREAD

**Issue by Gazpa47** [ClayCoffee/ClayTech#11]
** Describe 描述 **
Upon enabling claytech on server start I get this error message:
[12:00:41] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.1.5 (Is it up to date?)
java.lang.NoSuchFieldError: MACHINES_1
        at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:24) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:383) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:361) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:250) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

** To Reproduce 如何复现 **
Just starting my server and that error message is displayed

** Running Environment 运行环境 **
Tuinity

** Screenshots 截图 **

[12:00:41] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.1.5 (Is it up to date?)
java.lang.NoSuchFieldError: MACHINES_1
        at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:24) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:383) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:361) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:250) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"8499889"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by MrSynergist** [comment]
I'm having the same issue.

**Comment by ClayCoffee** [comment]
Confirmed.
