### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by 100petr** [ClayCoffee/ClayTech#13]
** Describe 描述 **
The plugin will not load. Error: https://hastebin.com/amisebijih.css

** To Reproduce 如何复现 **
Turn on the server

** Running Environment 运行环境 **
Paper v1_15_R1

CS-CoreLib vDEV - 83 (git 8081bb4f)
Slimefun vDEV - 486 (git b013247e)

Installed Addons (12)
Barrels vDEV - 11 (git abecba9c)
ClayTech v1.1.6
ElectricSpawners vDEV - 10 (git 6c891f7f)
SlimefunOreChunks vDEV - 8 (git 41e31ffc)
ExtraToolsPlugin vDEV - 9 (git 84269b5a)
SlimeXpansion vDEV - 15 (git 57438f88)
SoulJars vDEV - 15 (git dd58f105)
HotbarPets vDEV - 26 (git 7489ae00)
PrivateStorage vDEV - 11 (git b064863b)
ExtraGear vDEV - 9 (git e851d81d)
ColoredEnderChests vDEV - 10 (git 5dcddabb)
SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)

** Screenshots 截图 **

**Comment by ClayCoffee** [comment]
The url is broken

**Comment by 100petr** [comment]
It works for me.
```
[17:27:19] [Server thread/INFO]: [ClayTech] Enabling ClayTech v1.1.6
[17:27:19] [Server thread/INFO]: Init.
[17:27:19] [Server thread/INFO]: Init.
[17:27:19] [Server thread/INFO]: Init.
[17:27:19] [Server thread/INFO]: ClayTech By ClayCoffee.
[17:27:19] [Server thread/INFO]: Registering items..
[17:27:19] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.1.6 (Is it up to date?)
java.lang.NoSuchFieldError: BASIC_MACHINES
     at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:24) ~[?:?]
     at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:383) ~[?:?]
     at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:361) ~[?:?]
     at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:250) ~[?:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-205]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-205]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-205]
     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-205]
     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-205]
     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-205]
     at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-205]
     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-205]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[17:27:19] [Server thread/INFO]: [ClayTech] Disabling ClayTech v1.1.6
```

**Comment by ClayCoffee** [comment]
This is not my fault.
Please update your slimefun4 version!

**Comment by ClayCoffee** [comment]
It's too old.

**Comment by 100petr** [comment]
Too old? 
```
[18:19:06 ERROR]: Error occurred while enabling ClayTech v1.1.6 (Is it up to date?)
java.lang.NoSuchFieldError: BASIC_MACHINES
at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:24) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:383) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:361) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:250) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-208]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-208]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-208]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-208]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-208]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-208]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-208]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-208]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[18:19:06 INFO]: [ClayTech] Disabling ClayTech v1.1.6
```
I'm using the latest version and still:
CS-CoreLib vDEV - 84 (git 0d29dbee)
Slimefun vDEV - 487 (git ca6170e6)

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/ 
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/

**Comment by Diamondman121314** [comment]
This isn't Slimefun's fault. I realize earlier that MACHINES_1 was renamed to BASIC_MACHINES, but it's no longer like that. So the plugin needs to be updated to work with Slimefun again.
