### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by CodeChenL** [ClayCoffee/ClayTech#17]
游戏版本/Game version:1.15.2
核心版本/Core version:spigot-1.15.2
CS-CoreLib版本/CS corelib version:v1.6.3
slimefun版本/Slimefun version:Slimefun.v4.3-NIGHTLY-200428

错误代码段/Error code snippet

[18:22:55] [Server thread/INFO]: [ClayTech] Enabling ClayTech v1.1.8
[18:22:55] [Server thread/INFO]: 粘土科技 By ClayCoffee.
[18:22:55] [Server thread/INFO]: 注册粘液科技物品中...
[18:22:55] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.1.8 (Is it up to date?)
java.lang.NoSuchMethodError: me.mrCookieSlime.Slimefun.Objects.LockedCategory.<init>(Lorg/bukkit/NamespacedKey;Lorg/bukkit/inventory/ItemStack;[Lorg/bukkit/NamespacedKey;)V
        at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:24) ~[?:?]
        at club.claycoffee.ClayTech.implementation.items.Clay_basic.<init>(Clay_basic.java:26) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:360) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:250) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by ClayCoffee** [comment]
汉化版版本太旧，暂不支持

**Comment by CodeChenL** [comment]
能提供一个能兼容的汉化版本嘛

**Comment by CodeChenL** [comment]
> 汉化版版本太旧，暂不支持

能提供一个能兼容的汉化版本链接嘛

**Comment by ClayCoffee** [comment]
没有，建议使用英文版或等汉化版更新

**Comment by ClayCoffee** [comment]
1.1.6兼容，用这个版本
