### ISSUE TITLE
Can't change language [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#18]
** Describe 描述 **
While I change locale in config to:
`Locale: cs-CZ`
and make copy of en-US.yml renamed to cs-CZ.yml, I get this error in console and plugin doesn't work:
`[19:10:19] [Server thread/INFO]: [ClayTech] Enabling ClayTech v1.1.8
[19:10:19] [Server thread/INFO]: Loading Error: Locale not found.Disableing plugin..
[19:10:19] [Server thread/INFO]: [ClayTech] Disabling ClayTech v1.1.8
[19:10:19] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.1.8 (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_242]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97) ~[?:1.8.0_242]
	at club.claycoffee.ClayTech.utils.DataYML.reloadCustomConfig(DataYML.java:36) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:172) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-205]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[server.jar:git-Paper-205]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Paper-205]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[server.jar:git-Paper-205]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[server.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[server.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[server.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[server.jar:git-Paper-205]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

** To Reproduce 如何复现 **
See up.

** Running Environment 运行环境 **
`[19:04:50 INFO]: Paper v1_15_R1
[19:04:50 INFO]:
[19:04:50 INFO]: CS-CoreLib vDEV - 85 (git 4a7fce52)
[19:04:50 INFO]: Slimefun vDEV - 494 (git 2b9d109d)
[19:04:50 INFO]:
[19:04:50 INFO]: Installed Addons (19)
[19:04:50 INFO]: DyedBackpacks vDEV - 5 (git 129670c7)
[19:04:50 INFO]: ExtraTools vDEV - 12 (git 0b915279)
[19:04:50 INFO]: SoundMuffler vDEV - 10 (git 545192ca)
[19:04:50 INFO]: SlimefunOreChunks vDEV - 8 (git 41e31ffc)
[19:04:50 INFO]: SlimeXpansion vDEV - 15 (git 57438f88)
[19:04:50 INFO]: HotbarPets vDEV - 27 (git 975a8997)
[19:04:50 INFO]: ExtraGear vDEV - 9 (git e851d81d)
[19:04:50 INFO]: SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
[19:04:50 INFO]: ExoticGarden vDEV - 41 (git 0dd6b32e)
[19:04:50 INFO]: Barrels vDEV - 11 (git abecba9c)
[19:04:50 INFO]: ClayTech v1.1.8
[19:04:50 INFO]: LiteXpansion v1.0
[19:04:50 INFO]: ElectricSpawners vDEV - 10 (git 6c891f7f)
[19:04:50 INFO]: SoulJars vDEV - 16 (git 36dce719)
[19:04:50 INFO]: MobCapturer vDEV - 7 (git b61d3fbf)
[19:04:50 INFO]: SlimyTreeTaps vDEV - 10 (git 66d1dd72)
[19:04:50 INFO]: PrivateStorage vDEV - 11 (git b064863b)
[19:04:50 INFO]: ColoredEnderChests vDEV - 12 (git 8dbdc909)
[19:04:50 INFO]: ChestTerminal vDEV - 30 (git 04393688)`

** Screenshots 截图 **
Any, just error in log (console) and plugin doesn't work.

**Comment by bobhenl** [comment]
Btw I have claytech 1.1.9... not 1.1.8, there is wrong version writen.

**Comment by ClayCoffee** [comment]
This is not a bug.You should request a new language with your language file.
