### ISSUE TITLE
[BUG] Error occurred while enabling ClayTech v1.2.0-pre3 (Is it up to date?)

### ISSUE THREAD

**Issue by Scarlet2031** [ClayCoffee/ClayTech#28]
** Describe 描述 **
I restarted my server without changing anything but claytech suddenly got an error

** To Reproduce 如何复现 **

** Running Environment 运行环境 **
Error occurred while enabling ClayTech v1.2.0-pre3 (Is it up to date?)
java.lang.NoSuchFieldError: BUCKET_OF_OIL
at club.claycoffee.ClayTech.implementation.items.DrinkMakingStaff.<init>(DrinkMakingStaff.java:24) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:366) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:251) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-284]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-284]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-284]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-284]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-284]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-284]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-284]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-284]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/64282946/82131876-17836680-9804-11ea-8162-b2854256b3ae.png)

**Comment by izvanilla** [comment]
Any update? This is still a problem. Very sad.

**Comment by Scarlet2031** [comment]
still no update be patient :D

**Comment by ClayCoffee** [comment]
Now it works fine
