### ISSUE TITLE
[BUG] Log ERROR

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#31]
** Describe 描述 **
I'm getting log when server is starting.
** To Reproduce 如何复现 **
Start server with new version (pre1+).
`[02:56:23] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.2.0-pre3 (Is it up to date?)
java.lang.NoSuchFieldError: WITHER_PROOF_GLASS
	at club.claycoffee.ClayTech.ClayTechMachineRecipes.<clinit>(ClayTechMachineRecipes.java:200) ~[?:?]
	at club.claycoffee.ClayTech.implementation.items.PotionAffect_Weapons.<init>(PotionAffect_Weapons.java:17) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:362) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:251) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

** Running Environment 运行环境 **
Paper 301
[03:14:27 INFO]: Paper v1_15_R1
[03:14:27 INFO]:
[03:14:27 INFO]: CS-CoreLib vDEV - 85 (git 4a7fce52)
[03:14:27 INFO]: Slimefun vDEV - 508 (git af09dcdb)
[03:14:27 INFO]:
[03:14:27 INFO]: Installed Addons (20)
[03:14:27 INFO]: DyedBackpacks vDEV - 5 (git 129670c7)
[03:14:27 INFO]: ExtraTools vDEV - 14 (git a330a3dd)
[03:14:27 INFO]: SoundMuffler vDEV - 11 (git eb3f26f8)
[03:14:27 INFO]: SlimefunOreChunks vDEV - 8 (git 41e31ffc)
[03:14:27 INFO]: HotbarPets vDEV - 27 (git 975a8997)
[03:14:27 INFO]: ExtraGear vDEV - 9 (git e851d81d)
[03:14:27 INFO]: SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
[03:14:27 INFO]: ExoticGarden vDEV - 46 (git fe5109fe)
[03:14:27 INFO]: Barrels vDEV - 11 (git abecba9c)
[03:14:27 INFO]: ClayTech v1.2.0-pre3
[03:14:27 INFO]: Endrex v1.0.1
[03:14:27 INFO]: ElectricSpawners vDEV - 12 (git 4ae47f83)
[03:14:27 INFO]: LiteXpansion vDEV - 30 (git 4f4ddd6b)
[03:14:27 INFO]: SoulJars vDEV - 16 (git 36dce719)
[03:14:27 INFO]: MobCapturer vDEV - 7 (git b61d3fbf)
[03:14:27 INFO]: SlimyTreeTaps vDEV - 11 (git b64db511)
[03:14:27 INFO]: PrivateStorage vDEV - 11 (git b064863b)
[03:14:27 INFO]: TranscEndence vDEV - 8 (git 45d671f3)
[03:14:27 INFO]: ColoredEnderChests vDEV - 12 (git 8dbdc909)
[03:14:27 INFO]: ChestTerminal vDEV - 30 (git 04393688)

**Comment by ClayCoffee** [comment]
Works fine now.
