### ISSUE TITLE
[BUG] Broken again :/

### ISSUE THREAD

**Issue by Scarlet2031** [ClayCoffee/ClayTech#33]
Error occurred while enabling ClayTech v1.2.0-pre4 (Is it up to date?)
java.lang.NoSuchFieldError: WITHER_PROOF_OBSIDIAN
at club.claycoffee.ClayTech.ClayTechMachineRecipes.<clinit>(ClayTechMachineRecipes.java:169) ~[?:?]
at club.claycoffee.ClayTech.implementation.items.PotionAffect_Weapons.<init>(PotionAffect_Weapons.java:17) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:362) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:251) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-321]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

![image](https://user-images.githubusercontent.com/64282946/83029530-f79e3f00-a05c-11ea-9808-9b558812b93b.png)

**Comment by ClayCoffee** [comment]
can you use dev-5?
