### ISSUE TITLE
[BUG] Still Broken :////////////

### ISSUE THREAD

**Issue by Scarlet2031** [ClayCoffee/ClayTech#34]
** Describe 描述 **
Still broken......

** To Reproduce 如何复现 **
Error occurred while enabling ClayTech v1.2.0-dev5 (Is it up to date?)
java.lang.NoSuchFieldError: WITHER_PROOF_OBSIDIAN
	at club.claycoffee.ClayTech.ClayTechMachineRecipes.<clinit>(ClayTechMachineRecipes.java:169) ~[?:?]
	at club.claycoffee.ClayTech.implementation.items.PotionAffect_Weapons.<init>(PotionAffect_Weapons.java:17) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:362) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:251) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-321]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-321]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-321]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-321]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-321]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-321]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-321]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-321]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

** Running Environment 运行环境 **
>....=>.... [17:38:19 INFO]: Paper v1_15_R1
>.... [17:38:19 INFO]:
>.... [17:38:19 INFO]: CS-CoreLib vDEV - 85 (git 4a7fce52)
>.... [17:38:19 INFO]: Slimefun vRC - 12 (git da707a93)
>.... [17:38:19 INFO]:
>.... [17:38:19 INFO]: Installed Addons (8)
>.... [17:38:19 INFO]: ClayTech v1.2.0-dev5
>.... [17:38:19 INFO]: ExtraTools vDEV - 14 (git a330a3dd)
>.... [17:38:19 INFO]: LiteXpansion vDEV - 32 (git 8d9b202b)
>.... [17:38:19 INFO]: ExtraHeads vDEV - 14 (git 596a0822)
>.... [17:38:19 INFO]: HotbarPets vDEV - 27 (git 975a8997)
>.... [17:38:19 INFO]: ExtraGear vDEV - 9 (git e851d81d)
>.... [17:38:19 INFO]: TranscEndence vDEV - 10 (git 67f9b42f)
>.... [17:38:19 INFO]: SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/64282946/83053972-d4cf5300-a07b-11ea-87b5-47055b5b0925.png)

**Comment by j19mes** [comment]
i'm experiencing this as well

**Comment by 100petr** [comment]
Same problem.

**Comment by ClayCoffee** [comment]
Fixed
