### ISSUE TITLE
Error [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#41]
** Describe 描述 **
Hi, I got error in console!

** To Reproduce 如何复现 **
I just checked console, don't know but multiple plugins had this error too....

** Running Environment 运行环境 **
[03:53:54 INFO]: Paper v1_15_R1 354
[03:53:54 INFO]:
[03:53:54 INFO]: CS-CoreLib vDEV - 85 (git 4a7fce52)
[03:53:54 INFO]: Slimefun vDEV - 545 (git 3c3dd48e)
Build 8

** Errors 截图 **
```
[21:25:36 ERROR]: Could not pass event InventoryClickEvent to ClayTech v1.2.0-dev8
java.lang.IllegalStateException: Title not set
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.2.jar:git-Paper-354]
at club.claycoffee.ClayTech.listeners.RocketLauncherListener.InventoryMoveItemEvent(RocketLauncherListener.java:43) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor744.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-354]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-354]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2376) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-354]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-354]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by ClayCoffee** [comment]
not a bug
