### ISSUE TITLE
Error [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#45]
```
[19:21:27 ERROR]: Error occurred while enabling ClayTech v1.2.0-dev12 (Is it up to date?)
java.lang.NoSuchFieldError: instance
at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:26) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:427) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:402) ~[?:?]
at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:270) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-372]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-372]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-372]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-372]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-372]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-372]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-372]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Scarlet2031** [comment]
slimefun master has been update and claytech not , be patient :D

**Comment by j19mes** [comment]
Yeah same issue here, can't wait for the update :)
