### ISSUE TITLE
Error while startup - can't load [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#52]
** Describe 描述 **
Plugin can't load due to following error.
** To Reproduce 如何复现 **
Try to load plugin on specified versions.
```
[14:59:49] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.2.0-dev16 (Is it up to date?)
java.lang.IllegalAccessError: class club.claycoffee.ClayTech.ClayTechItems tried to access private field io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.instance (club.claycoffee.ClayTech.ClayTechItems is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6c930573; io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7166e463)
	at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:26) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:429) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:404) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:270) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-79]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-79]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

** Running Environment 运行环境 **
```
[15:57:55 INFO]: This server is running Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[15:57:55 INFO]: Checking version, please wait...
[15:57:55 INFO]: Previous version: git-Paper-77 (MC: 1.16.1)
[15:57:55 INFO]: You are running the latest version
[15:57:47 INFO]: Paper v1_16_R1
[15:57:47 INFO]:
[15:57:47 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
[15:57:47 INFO]: Slimefun vDEV - 580 (git c516cab2)
[15:57:47 INFO]:
[15:57:47 INFO]: Installed Addons (19)
[15:57:47 INFO]: DyedBackpacks vDEV - 9 (git c42435c1)
[15:57:47 INFO]: ExtraTools vDEV - 14 (git a330a3dd)
[15:57:47 INFO]: SoundMuffler vDEV - 12 (git 7303b3a9)
[15:57:47 INFO]: SlimefunOreChunks vDEV - 9 (git 88dd72b0)
[15:57:47 INFO]: HotbarPets vDEV - 28 (git 89eb962c)
[15:57:47 INFO]: ExtraGear vDEV - 10 (git 892256da)
[15:57:47 INFO]: SlimefunLuckyBlocks vDEV - 25 (git c24d0770)
[15:57:47 INFO]: ExoticGarden vDEV - 54 (git 304c3908)
[15:57:47 INFO]: Barrels vDEV - 11 (git abecba9c)
[15:57:47 INFO]: ClayTech v1.2.0-dev16
[15:57:47 INFO]: ElectricSpawners vDEV - 16 (git b673150e)
[15:57:47 INFO]: LiteXpansion vDEV - 42 (git 2df1e3bf)
[15:57:47 INFO]: SoulJars vDEV - 16 (git 36dce719)
[15:57:47 INFO]: MobCapturer vDEV - 9 (git 0b1285f0)
[15:57:47 INFO]: SlimyTreeTaps vDEV - 12 (git d5557288)
[15:57:47 INFO]: PrivateStorage vDEV - 12 (git 462f8770)
[15:57:47 INFO]: ColoredEnderChests vDEV - 14 (git 51eb3afb)
[15:57:47 INFO]: TranscEndence vDEV - 13 (git a74b837f)
[15:57:47 INFO]: ChestTerminal vDEV - 32 (git b3ce940e)
```

Btw why it's still broking? 😅 I'm reporting something with startup almost every week...

**Comment by bobhenl** [comment]
And could I download new ver?

**Comment by ClayCoffee** [comment]
https://github.com/ClayCoffee/ClayTech/runs/852810352
download artifacts here and disable auto update
