### ISSUE TITLE
[BUG]插件无法启动

### ISSUE THREAD

**Issue by ppfirework** [ClayCoffee/ClayTech#57]
** Describe 描述 **

** To Reproduce 如何复现 **
下载最新版的粘土科技 开服 然后报错
log：
 [ClayTech] Enabling ClayTech v1.2.0-dev17
[21:30:58 INFO]: ClayTech By ClayCoffee.
[21:30:58 INFO]: Registering items..
[21:30:58 ERROR]: Error occurred while enabling ClayTech v1.2.0-dev17 (Is it up to date?)
java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.instance()Lio/github/thebusybiscuit/slimefun4/implementation/SlimefunPlugin;
        at club.claycoffee.ClayTech.ClayTechItems.<clinit>(ClayTechItems.java:394) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerMachines(ClayTech.java:393) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:370) ~[?:?]
        at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:236) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:932) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.Bukkit.reload(Bukkit.java:688) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-100]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-100]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-100]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-100]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-100]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-100]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
** Running Environment 运行环境 **
jre 251
paper b100z
粘液科技最新版

** Screenshots 截图 **
截图就不用了吧

**Comment by ClayCoffee** [comment]
你绝对没有更新到最新版本
