### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#59]
** Describe 描述 **
Error in console.

** To Reproduce 如何复现 **
Install plugin?

** Running Environment 运行环境 **
Paper 101, 1.16.1

** Errors 截图 **
```
[11:22:42 ERROR]: Could not pass event BlockBreakEvent to ClayTech v1.2.1
java.lang.NoClassDefFoundError: club/claycoffee/ClayTech/utils/Food
at club.claycoffee.ClayTech.listeners.FoodDropListener.BlockBreakEvent(FoodDropListener.java:20) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor799.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-101]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-101]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-101]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:249) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1389) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-101]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by ClayCoffee** [comment]
update
