### ISSUE TITLE
Error while loading [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#62]
```
[01:53:34] [Server thread/INFO]: [Slimefun] Parent "claytech:claycategory" for Category "claytech:claycategory6" was not found, probably just disabled.
[01:53:34] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.2.4 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class club.claycoffee.ClayTech.implementation.items.Rockets$1 can not implement io.github.thebusybiscuit.slimefun4.core.handlers.BlockPlaceHandler, because it is not an interface (io.github.thebusybiscuit.slimefun4.core.handlers.BlockPlaceHandler is in un
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at club.claycoffee.ClayTech.implementation.items.Rockets.<init>(Rockets.java:46) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:391) ~[?:?]
	at club.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:236) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[01:53:34] [Server thread/INFO]: [ClayTech] Disabling ClayTech v1.2.4
```

```
>.... [01:49:23 INFO]: Paper v1_16_R1
>.... [01:49:23 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
>.... [01:49:23 INFO]: Slimefun vDEV - 621 (git f50d1d2f)
>.... [01:49:23 INFO]: Metrics build: #14
>.... [01:49:23 INFO]:
>.... [01:49:23 INFO]: Installed Addons: (22)
>.... [01:49:23 INFO]: DyedBackpacks vDEV - 9 (git c42435c1)
>.... [01:49:23 INFO]: ExtraTools vDEV - 18 (git 634462af)
>.... [01:49:23 INFO]: SlimefunOreChunks vDEV - 9 (git 88dd72b0)
>.... [01:49:23 INFO]: Residence v4.9.1.6
>.... [01:49:23 INFO]: EcoPower vDEV - 1 (git 53445ee5)
>.... [01:49:23 INFO]: HotbarPets vDEV - 30 (git a434e3aa)
>.... [01:49:23 INFO]: ExtraGear vDEV - 11 (git 2682d2a4)
>.... [01:49:23 INFO]: SlimefunLuckyBlocks vDEV - 27 (git 2798a937)
>.... [01:49:23 INFO]: ExoticGarden vDEV - 56 (git e7024e9a)
>.... [01:49:23 INFO]: Barrels vDEV - 12 (git 0f66f4c9)
>.... [01:49:23 INFO]: ClayTech v1.2.4
>.... [01:49:23 INFO]: Endrex v1.0.3-b1
>.... [01:49:23 INFO]: ElectricSpawners vDEV - 17 (git 4ce66b94)
>.... [01:49:23 INFO]: LiteXpansion vDEV - 48 (git 47e9eec9)
>.... [01:49:23 INFO]: SoulJars vDEV - 16 (git 36dce719)
>.... [01:49:23 INFO]: MobCapturer vDEV - 10 (git 33cdceb3)
>.... [01:49:23 INFO]: SlimyTreeTaps vDEV - 14 (git b97239fb)
>.... [01:49:23 INFO]: PrivateStorage vDEV - 13 (git fa5cc2f9)
>.... [01:49:23 INFO]: ColoredEnderChests vDEV - 16 (git c987c764)
>.... [01:49:23 INFO]: TranscEndence vDEV - 17 (git 056982d3)
>.... [01:49:23 INFO]: CMI v8.7.5.3
>.... [01:49:23 INFO]: ChestTerminal vDEV - 34 (git 5f73deb7
```

**Comment by bobhenl** [comment]
Please @ClayCoffee could you release new version when you fix bugs that blocks loading?

**Comment by ClayCoffee** [comment]
> Please @ClayCoffee could you release new version when you fix bugs that blocks loading?

https://github.com/ClayCoffee/ClayTech/suites/1020595600/artifacts/13398209

disable the auto updater then use this jar until the new version comes out
