### ISSUE TITLE
Error in console [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#65]
** Describe 描述 **
Hi, I got this error, probably when someone teleported to residence with claytech mechanisms, from error probably associated with residence tp? 

** To Reproduce 如何复现 **
Teleports to res, where are claytech mechanisms.

** Running Environment 运行环境 **
```
.=>.... [01:14:12 INFO]: This server is running Paper version git-Paper-133 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
>.... [01:14:12 INFO]: Checking version, please wait...
>.... [01:14:12 INFO]: Previous version: git-Paper-132 (MC: 1.16.1)
>.... [01:14:12 INFO]: You are running the latest version
>....=>.... [01:14:14 INFO]: This Server uses the following setup of Slimefun:
>.... [01:14:14 INFO]: Paper v1_16_R1
>.... [01:14:14 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
>.... [01:14:14 INFO]: Slimefun vDEV - 627 (git 7de9dd66)
>.... [01:14:14 INFO]: Metrics build: #14
>.... [01:14:14 INFO]:
>.... [01:14:14 INFO]: Installed Addons: (21)
>.... [01:14:14 INFO]: DyedBackpacks vDEV - 9 (git c42435c1)
>.... [01:14:14 INFO]: ExtraTools vDEV - 18 (git 634462af)
>.... [01:14:14 INFO]: SlimefunOreChunks vDEV - 9 (git 88dd72b0)
>.... [01:14:14 INFO]: Residence v4.9.1.6
>.... [01:14:14 INFO]: EcoPower vDEV - 1 (git 53445ee5)
>.... [01:14:14 INFO]: HotbarPets vDEV - 30 (git a434e3aa)
>.... [01:14:14 INFO]: ExtraGear vDEV - 11 (git 2682d2a4)
>.... [01:14:14 INFO]: SlimefunLuckyBlocks vDEV - 27 (git 2798a937)
>.... [01:14:14 INFO]: ExoticGarden vDEV - 56 (git e7024e9a)
>.... [01:14:14 INFO]: Barrels vDEV - 14 (git 1563de94)
>.... [01:14:14 INFO]: ClayTech v1.2.5
>.... [01:14:14 INFO]: ElectricSpawners vDEV - 17 (git 4ce66b94)
>.... [01:14:14 INFO]: LiteXpansion vDEV - 48 (git 47e9eec9)
>.... [01:14:14 INFO]: SoulJars vDEV - 16 (git 36dce719)
>.... [01:14:14 INFO]: MobCapturer vDEV - 10 (git 33cdceb3)
>.... [01:14:14 INFO]: SlimyTreeTaps vDEV - 14 (git b97239fb)
>.... [01:14:14 INFO]: PrivateStorage vDEV - 13 (git fa5cc2f9)
>.... [01:14:14 INFO]: ColoredEnderChests vDEV - 16 (git c987c764)
>.... [01:14:14 INFO]: TranscEndence vDEV - 17 (git 056982d3)
>.... [01:14:14 INFO]: CMI v8.7.5.5
>.... [01:14:14 INFO]: ChestTerminal vDEV - 34 (git 5f73deb7)
```

** Errors 截图 **
```
>.... [01:10:42 ERROR]: Could not pass event PlayerTeleportEvent to ClayTech v1.2.5
java.lang.NullPointerException: null
at club.claycoffee.ClayTech.listeners.PlanetListener.PlayerTeleportEvent(PlanetListener.java:422) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor805.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-133]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:787) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522) ~[patched_1.16.1.jar:git-Paper-133]
at com.bekvon.bukkit.residence.protection.ClaimedResidence.performInstantTp(ClaimedResidence.java:1398) ~[?:?]
at com.bekvon.bukkit.residence.protection.ClaimedResidence.tpToResidence(ClaimedResidence.java:1347) ~[?:?]
at com.bekvon.bukkit.residence.commands.tp.perform(tp.java:41) ~[?:?]
at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-133]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-133]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by ClayCoffee** [comment]
> ** Describe 描述 **
> Hi, I got this error, probably when someone teleported to residence with claytech mechanisms, from error probably associated with residence tp?
> 
> ** To Reproduce 如何复现 **
> Teleports to res, where are claytech mechanisms.
> 
> ** Running Environment 运行环境 **
> 
> ```
> .�=>.... [01:14:12 INFO]: This server is running Paper version git-Paper-133 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
> >.... [01:14:12 INFO]: Checking version, please wait...
> >.... [01:14:12 INFO]: Previous version: git-Paper-132 (MC: 1.16.1)
> >.... [01:14:12 INFO]: You are running the latest version
> >....�=>.... [01:14:14 INFO]: This Server uses the following setup of Slimefun:
> >.... [01:14:14 INFO]: Paper v1_16_R1
> >.... [01:14:14 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
> >.... [01:14:14 INFO]: Slimefun vDEV - 627 (git 7de9dd66)
> >.... [01:14:14 INFO]: Metrics build: #14
> >.... [01:14:14 INFO]:
> >.... [01:14:14 INFO]: Installed Addons: (21)
> >.... [01:14:14 INFO]: DyedBackpacks vDEV - 9 (git c42435c1)
> >.... [01:14:14 INFO]: ExtraTools vDEV - 18 (git 634462af)
> >.... [01:14:14 INFO]: SlimefunOreChunks vDEV - 9 (git 88dd72b0)
> >.... [01:14:14 INFO]: Residence v4.9.1.6
> >.... [01:14:14 INFO]: EcoPower vDEV - 1 (git 53445ee5)
> >.... [01:14:14 INFO]: HotbarPets vDEV - 30 (git a434e3aa)
> >.... [01:14:14 INFO]: ExtraGear vDEV - 11 (git 2682d2a4)
> >.... [01:14:14 INFO]: SlimefunLuckyBlocks vDEV - 27 (git 2798a937)
> >.... [01:14:14 INFO]: ExoticGarden vDEV - 56 (git e7024e9a)
> >.... [01:14:14 INFO]: Barrels vDEV - 14 (git 1563de94)
> >.... [01:14:14 INFO]: ClayTech v1.2.5
> >.... [01:14:14 INFO]: ElectricSpawners vDEV - 17 (git 4ce66b94)
> >.... [01:14:14 INFO]: LiteXpansion vDEV - 48 (git 47e9eec9)
> >.... [01:14:14 INFO]: SoulJars vDEV - 16 (git 36dce719)
> >.... [01:14:14 INFO]: MobCapturer vDEV - 10 (git 33cdceb3)
> >.... [01:14:14 INFO]: SlimyTreeTaps vDEV - 14 (git b97239fb)
> >.... [01:14:14 INFO]: PrivateStorage vDEV - 13 (git fa5cc2f9)
> >.... [01:14:14 INFO]: ColoredEnderChests vDEV - 16 (git c987c764)
> >.... [01:14:14 INFO]: TranscEndence vDEV - 17 (git 056982d3)
> >.... [01:14:14 INFO]: CMI v8.7.5.5
> >.... [01:14:14 INFO]: ChestTerminal vDEV - 34 (git 5f73deb7)
> ```
> 
> ** Errors 截图 **
> 
> ```
> >.... [01:10:42 ERROR]: Could not pass event PlayerTeleportEvent to ClayTech v1.2.5
> java.lang.NullPointerException: null
> at club.claycoffee.ClayTech.listeners.PlanetListener.PlayerTeleportEvent(PlanetListener.java:422) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor805.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-133]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:787) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522) ~[patched_1.16.1.jar:git-Paper-133]
> at com.bekvon.bukkit.residence.protection.ClaimedResidence.performInstantTp(ClaimedResidence.java:1398) ~[?:?]
> at com.bekvon.bukkit.residence.protection.ClaimedResidence.tpToResidence(ClaimedResidence.java:1347) ~[?:?]
> at com.bekvon.bukkit.residence.commands.tp.perform(tp.java:41) ~[?:?]
> at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-133]
> at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-133]
> at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
> at java.lang.Thread.run(Thread.java:832) [?:?]
> ```

https://github.com/ClayCoffee/ClayTech/suites/1026062720/artifacts/13527565
new version download link
