### ISSUE TITLE
[BUG]FOOD_CHALKING_MACHINE cannot be placed

### ISSUE THREAD

**Issue by Xzavier0722** [ClayCoffee/ClayTech#68]
** Describe 描述 **
An exception thrown while putting down the food chalking machine.
With the error-report as below:
Java Environment:
  Operating System: Linux
  Java Version: 1.8.0_221

Server Software: Paper
  Build: git-Paper-133 (MC: 1.16.1)
  Minecraft: 1.16.1-R0.1-SNAPSHOT

Slimefun Environment:
  CS-CoreLib vDEV - 90 (git 9dd4a1cf)
  Slimefun v4.3-dev-200810
  Caused by: ClayTech v1.2.7

Installed Addons (3)
  + CMI 8.7.5.5
  + EcoPower DEV - 1 (git 53445ee5)
  + ClayTech 1.2.7

Installed Plugins (37):
  + HackedCore 2.59.0
  + WhiteList 0.1
  + GroupManager 2.5 (Phoenix)
  + IronElevators 1.5
  + SpigotPing 2.6
  + SkinsRestorer 13.8.3
  + FastAsyncWorldEdit 1.16.1
  + ImageOnMap 4.0
  + CS-CoreLib DEV - 90 (git 9dd4a1cf)
  + mcMMO 2.1.140-SNAPSHOT
  + ViaVersion 3.1.0
  + EpicPluginLib 1.6
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + PlayMoreSounds 3.1
  + CommandFilter 1.4.3
  + dynmap 3.1-beta-1-367
  + TitleManager 2.3.1
  + WorldEdit 1.16-311;e39c29d
  + EntityTrackerFixer 1.3.1
  + HackedServer 2.67.0
  + UltimateTimber 2.0.8
  + HeadDatabase 4.12.6
  + ProtocolLib 4.6.0-SNAPSHOT-b473
  + React 6.633
  + CoreProtect 19.1
  + BKCommonLib 1.16.1-v1
  + AuthMe 5.6.0-SNAPSHOT-b2409
  + ColorMOTD 1.5.3
  + LightCleaner 1.16.1-v1
  + LockettePro 2.10.2
  + QuickShop 4.0.4.5
  + CMI 8.7.5.5
  + Residence 4.9.1.0
  + Slimefun 4.3-dev-200810
  + EcoPower DEV - 1 (git 53445ee5)
  + ClayTech 1.2.7
  + CMIPaperLib 1.0.0

Block Info:
  World: world
  X: 12934
  Y: 63
  Z: 18130
  Material: PLAYER_HEAD
  Block Data: org.bukkit.craftbukkit.v1_16_R1.block.impl.CraftSkullPlayer
  State: org.bukkit.craftbukkit.v1_16_R1.block.CraftSkull
Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: CLAY_FOOD_CHALKING_MACHINE
  Inventory: true
  Data: {"energy-charge":"288","id":"CLAY_FOOD_CHALKING_MACHINE"}

Stacktrace:

java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.tick(AContainer.java:265)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$2.tick(AContainer.java:216)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:127)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tick(TickerTask.java:115)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:70)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$start$4(TickerTask.java:183)
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

** To Reproduce 如何复现 **
Put down it.

** Running Environment 运行环境 **
It should contain in report.

** Screenshots 截图 **
None

**Comment by dixiatielu** [comment]
我遇到了同样的bug……
