### ISSUE TITLE
[BUG]Could not pass event BlockBreakEvent to ClayTech v1.2.8

### ISSUE THREAD

**Issue by dixiatielu** [ClayCoffee/ClayTech#69]
**Describe 描述**
破坏任意方块时后台不停报错
```
[19:14:57] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ClayTech v1.2.8
java.lang.NoClassDefFoundError: cn/claycoffee/ClayTech/utils/Food
	at cn.claycoffee.ClayTech.listeners.FoodEatListener.PlayerInteractEvent(FoodEatListener.java:21) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor416.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:434) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1465) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-385]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[19:15:13] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ClayTech v1.2.8
java.lang.NoClassDefFoundError: cn/claycoffee/ClayTech/utils/Food
	at cn.claycoffee.ClayTech.listeners.FoodDropListener.BlockBreakEvent(FoodDropListener.java:20) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor417.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:321) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:280) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:246) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1365) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1233) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-385]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: cn.claycoffee.ClayTech.utils.Food
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-385]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 23 more
```

**To Reproduce 如何复现**
放置食物打粉机，然后放入食物，然后破坏食物打粉机。
之后破坏任意方块就会报`Could not pass event BlockBreakEvent to ClayTech v1.2.8`
**Running Environment 运行环境**
![image](https://user-images.githubusercontent.com/29675002/90886621-50c00980-e3e5-11ea-8932-2ddf6c3a5ed9.png)

Ubuntu 18.04 LTS
Openjdk 8 64位
**Screenshots 截图**
暂无

**Comment by ClayCoffee** [comment]
不能复现，请检查自身服务端问题
遇到这种错误建议重新下载插件

**Comment by dixiatielu** [comment]
这是1.2.8版本的错误 降级到1.2.7后暂时正常（不过放置打粉机后直接消失），不过食物打粉机又报了个错……我再开一个issue发……

**Comment by ClayCoffee** [comment]
1.2.8不能复现
我说的就是1.2.8啊..
你从哪里下的

**Comment by ClayCoffee** [comment]
你这个复现方式都错了.. 就算有问题也应该是 拿着食物破坏方块有问题
而不是你这种的触发方式 我刚刚又测试了一遍，完全没有任何问题

**Comment by dixiatielu** [comment]
> 1.2.8不能复现
> 我说的就是1.2.8啊..
> 你从哪里下的

Github Action

我本来看到今天上午的commit修复了消失的bug，就从Github Action下载最新版，结果就出这问题……

**Comment by ClayCoffee** [comment]
> > 1.2.8不能复现
> > 我说的就是1.2.8啊..
> > 你从哪里下的
> 
> Github Action
> 
> 我本来看到今天上午的commit修复了消失的bug，就从Github Action下载最新版，结果就出这问题……

重新下一次，再装上试试

**Comment by dixiatielu** [comment]
> > > 1.2.8不能复现
> > > 我说的就是1.2.8啊..
> > > 你从哪里下的
> > 
> > 
> > Github Action
> > 我本来看到今天上午的commit修复了消失的bug，就从Github Action下载最新版，结果就出这问题……
> 
> 重新下一次，再装上试试

我现在服里有玩家，不好重启😂😂😂

不过我装上1.2.8就会被自动“更新”为1.2.7😂😂😂😂

**Comment by ClayCoffee** [comment]
> > > > 1.2.8不能复现
> > > > 我说的就是1.2.8啊..
> > > > 你从哪里下的
> > > 
> > > 
> > > Github Action
> > > 我本来看到今天上午的commit修复了消失的bug，就从Github Action下载最新版，结果就出这问题……
> > 
> > 
> > 重新下一次，再装上试试
> 
> 我现在服里有玩家，不好重启😂😂😂
> 
> 不过我装上1.2.8就会被自动“更新”为1.2.7😂😂😂😂

关掉自动更新

**Comment by dixiatielu** [comment]
刚刚上线试了一下，最新版1.2.8重新安装后确实不能复现……
不知道当时玩家是干了啥……
先Close了
