### ISSUE TITLE
[Help Wanted]粘土燃料不生成

### ISSUE THREAD

**Issue by dixiatielu** [ClayCoffee/ClayTech#76]
玩家反馈现在找不到粘土燃料（之前可以）
我觉得以下内容可能有关
启动服务器时报Waring：
```
[16:35:09 INFO]: 在注册物品时发生错误:
[16:35:09 WARN]: java.lang.NullPointerException
[16:35:09 WARN]:        at cn.claycoffee.ClayTech.implementation.Planets.Moon.getDefaultPopulators(Moon.java:69)
[16:35:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.initWorld(MinecraftServer.java:501)
[16:35:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createWorld(CraftServer.java:1075)
[16:35:09 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:548)
[16:35:09 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:320)
[16:35:09 WARN]:        at cn.claycoffee.ClayTech.api.Planet.register(Planet.java:144)
[16:35:09 WARN]:        at cn.claycoffee.ClayTech.implementation.Planets.Moon.<init>(Moon.java:26)
[16:35:09 WARN]:        at cn.claycoffee.ClayTech.ClayTech.registerPlanets(ClayTech.java:422)
[16:35:09 WARN]:        at cn.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:239)
[16:35:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:35:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:35:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:35:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[16:35:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[16:35:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[16:35:09 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[16:35:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
[16:35:09 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
在加载“CMoon”世界方块的时候，有像这样的一大堆info：
```
[16:35:17 INFO]: [Slimefun] Ignoring duplicate block @ 3,091, 15, 2,830 (COPPER_ORE -> CLAY_FUSION_ORE)
[16:35:17 INFO]: [Slimefun] Ignoring duplicate block @ 3,091, 15, 2,831 (COPPER_ORE -> CLAY_FUSION_ORE)
[16:35:17 INFO]: [Slimefun] Ignoring duplicate block @ 3,103, 15, 2,905 (COPPER_ORE -> CLAY_FUSION_ORE)
[16:35:17 INFO]: [Slimefun] Ignoring duplicate block @ 3,096, 18, 2,760 (COPPER_ORE -> CLAY_FUSION_ORE)
[16:35:17 INFO]: [Slimefun] Ignoring duplicate block @ 3,096, 18, 2,761 (COPPER_ORE -> CLAY_FUSION_ORE)
```
粘液科技版本信息：
![image](https://user-images.githubusercontent.com/29675002/91152718-ea433000-e6f1-11ea-9e02-ae5979360236.png)
请问有什么方法解决此问题？

**Comment by ClayCoffee** [comment]
"[Slimefun] Ignoring duplicate block @ 3,091, 15, 2,830"
这种是有重复方块
然后那个NPE应该是bug，但是不关乎矿物生成
我一会再看看

**Comment by ClayCoffee** [comment]
你有没有禁用月球上的矿物？

**Comment by dixiatielu** [comment]
> 你有没有禁用月球上的矿物？

没有……
配置文件：
![image](https://user-images.githubusercontent.com/29675002/91649880-03a9fa80-eaab-11ea-918b-f3d9741cdf09.png)

**Comment by ClayCoffee** [comment]
logs发过来。你这个配置文件不对。
估计是mv加载在claytech之前导致的问题，理应是不会出现这种情况的。
建议升级你的mv版本到4.1.0

**Comment by dixiatielu** [comment]
> logs发过来。你这个配置文件不对。
> 估计是mv加载在claytech之前导致的问题，理应是不会出现这种情况的。
> 建议升级你的mv版本到4.1.0

mv指multiverse?我没安装这个插件

log[在这里](https://paste.ubuntu.com/p/kMPsRdhnnf/)

**Comment by xiaozhiyl** [comment]
最新版还是没有修复吗？我用了4.1.0的mv 还是没办法写入world配置文件 世界是生成出来了 但是就是不写入配置文件

**Comment by ClayCoffee** [comment]
> 最新版还是没有修复吗？我用了4.1.0的mv 还是没办法写入world配置文件 世界是生成出来了 但是就是不写入配置文件

Paper+mv4.1.0无法复现

**Comment by xiaozhiyl** [comment]
那要怎么解决呢？
