### ISSUE TITLE
[BUG]世界生成问题？

### ISSUE THREAD

**Issue by xiaozhiyl** [ClayCoffee/ClayTech#77]
请问新版本生成的世界为什么会出现问题呢?Multiverse-Core里的world配置文件也没有写入月球和其他星球的世界信息 但是传送到月球就是这样的？是生成出现了问题嘛？下图是到月球的景象 一片虚空 什么都没有 等待几分钟也没有东西
![2020-08-27_17 40 34](https://user-images.githubusercontent.com/57853246/91424691-b5b7ab80-e88c-11ea-9008-48aea359230d.png)

**Comment by xiaozhiyl** [comment]
版本是1.16.1的 后台没有任何报错信息 如需log可以提供

**Comment by ClayCoffee** [comment]
尝试一下删除CMoon文件夹，然后重启服务器
接着把服务器log发出来 从启动到进入月球的所有日志

**Comment by xiaozhiyl** [comment]
这是传送到月球的方法 使用MV没办法传送过去 配置文件里面没有那个世界只能用这个办法传送过去 
![QQ截图20200827192641](https://user-images.githubusercontent.com/57853246/91436791-6167f800-e89b-11ea-92a4-9bcad2b3ca24.png)
![QQ截图20200827192652](https://user-images.githubusercontent.com/57853246/91436795-63ca5200-e89b-11ea-8213-ba76f16a3d2c.png)
[2020-08-27-20.log.gz](https://github.com/ClayCoffee/ClayTech/files/5136066/2020-08-27-20.log.gz)

**Comment by ClayCoffee** [comment]
`java.lang.NullPointerException
[17:33:42] [Server thread/WARN]: 	at cn.claycoffee.ClayTech.implementation.Planets.Moon.getDefaultPopulators(Moon.java:69)
[17:33:42] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.initWorld(MinecraftServer.java:485)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createWorld(CraftServer.java:1154)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:570)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325)
[17:33:42] [Server thread/WARN]: 	at cn.claycoffee.ClayTech.api.Planet.register(Planet.java:144)
[17:33:42] [Server thread/WARN]: 	at cn.claycoffee.ClayTech.implementation.Planets.Moon.<init>(Moon.java:26)
[17:33:42] [Server thread/WARN]: 	at cn.claycoffee.ClayTech.ClayTech.registerPlanets(ClayTech.java:422)
[17:33:42] [Server thread/WARN]: 	at cn.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:239)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[17:33:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[17:33:42] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[17:33:42] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[17:33:42] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941)
[17:33:42] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:33:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by ClayCoffee** [comment]
与ClayCoffee#76重复

**Comment by xiaozhiyl** [comment]
请问这个大概需要多久能修复呢？
