### ISSUE TITLE
[BUG]服务端无法加载粘土科技

### ISSUE THREAD

**Issue by Jerry4116** [ClayCoffee/ClayTech#84]
** Describe 描述 **
服务端启动时遇到与#62相同的情况，详见下方

** To Reproduce 如何复现 **
启动服务端（paper-189.jar）

** Running Environment 运行环境 **
服务端：paper-189
java：openjdk version "1.8.0_265"
插件列表：
MineTinker v1.6 (Flo56958) - ON
CS-CoreLib vDEV - 91 (git e42a05d1) (A lot of awesome people) - ON
Slimefun v4.3-stable-200802 (The Slimefun 4 Community) - ON
HotbarPets vDEV - 30 (git a434e3aa) (TheBusyBiscuit) - ON
FogusCore v1.9.9 (JLX) - ON
ExoticGarden vDEV - 56 (git e7024e9a) (The Slimefun 4 Community) - ON
BossLand v0.5 (Eliminator) - ON
ClayTech v1.2.15-hotfix (ClayCoffee) - OFF
AsteroidBelt v1.0.4 (?) - OFF
SunLight v2.4.5a 

** Screenshots 截图 **

[19:00:53 INFO]: [ClayTech] Enabling ClayTech v1.2.15-hotfix
[19:00:53 INFO]: 粘土科技 By ClayCoffee.
[19:00:53 INFO]: 注册粘液科技物品中...
[19:00:53 INFO]: [Slimefun] Parent "claytech:claycategory" for Category "claytech:claycategory6" was not found, probably just disabled.
[19:00:53 ERROR]: Error occurred while enabling ClayTech v1.2.15-hotfix (Is it up to date?)
java.lang.IncompatibleClassChangeError: class cn.claycoffee.ClayTech.implementation.items.Rockets$1 has interface io.github.thebusybiscuit.slimefun4.core.handlers.BlockPlaceHandler as super class
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_265]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_265]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-189]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
        at cn.claycoffee.ClayTech.implementation.items.Rockets.<init>(Rockets.java:44) ~[?:?]
        at cn.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:354) ~[?:?]
        at cn.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[19:00:53 INFO]: [ClayTech] Disabling ClayTech v1.2.15-hotfix

**Comment by Jerry4116** [comment]
插件列表中误写成了v1.2.14，实际上我测试了v1.2.14、v1.2.15、v1.2.15-hotfix均无法加载，且仅存在Slimefun、ClayTech、CS-Corelib和AsteroidBelt时也无法加载

**Comment by Jerry4116** [comment]
已解决：需使用开发版而非稳定版粘液科技作为前置。希望在Readme或wiki中注明。
