### ISSUE TITLE
Auto update error in console [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#89]
** Describe 描述 **
Hi, in console I'm getting this error, prob. connected to auto update.

** To Reproduce 如何复现 **
I just have installed plugin, and probably update wanted to execute.

** Running Environment 运行环境 **
Cs-Core lib 91
Slimefun 719 
Claytech 1.2.17
Paper 1.16.3 228

** Logs 截图 **
```
[09:16:12] [Craft Scheduler Thread - 13/INFO]: Could not perform update. Is the Github down?
[09:16:12] [Craft Scheduler Thread - 13/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/ClayCoffee/ClayTech/releases
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at cn.claycoffee.ClayTech.ClayTechUpdater$1.run(ClayTechUpdater.java:33)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:16:12] [Craft Scheduler Thread - 13/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ClayCoffee** [comment]
Not a bug.
