### ISSUE TITLE
[BUG] WorldGuard required?

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#93]
** Describe 描述 **
Error, rpobably because I don't have worldguard plugin.
```
[18:24:11] [Server thread/ERROR]: Error occurred while enabling ClayTech v1.2.18 (Is it up to date?)
java.lang.NoClassDefFoundError: com/wimbli/WorldBorder/WorldBorder
	at cn.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: com.wimbli.WorldBorder.WorldBorder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-259]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 11 more
[18:24:11] [Server thread/INFO]: [ClayTech] Disabling ClayTech v1.2.18
```

** To Reproduce 如何复现 **
Don't use worldguard.

** Running Environment 运行环境 **
CS-core: 91
Sf: 738
Paper 1.16.4
Claytech 1.2.18

** Screenshots 截图 **

**Comment by ClayCoffee** [comment]
Sorry, I forgot to remove the debug code... Fixed.
